### ISSUE TITLE
Purpose of this library

### ISSUE THREAD

**Issue by dmitriyparasochka** [CryptoManiac/AssemblyLoader#51]
For what purpose you develop this library? 
Why did you develop it from scratch? 
Why don't you use libraries like mono.cecil or dnSpy?

**Comment by CryptoManiac** [comment]
Of course you are correct, there are a lot of parsers and the bytecode analyzers. Mainly, this is just an attempt to revive some old and forgotten memories. In that sense, it is probably correct that usage of mono.cecil wouldn't be better than writing a parser of your own.
